### ISSUE TITLE
Everything else than Error or Fatal messages will be ignored

### ISSUE THREAD

**Issue by corrtarr** [datalust/nlog-targets-seq#33] opened 2018-05-17 12:19 UTC
We are sending events to our seq server by using an API key.
When using minimum level (API key configuration page on SEQ) Info no Info level events are accepted on the seq server. Error and fatal level events will get through. Same for Debug or Verbose. Only accepting all events (setting minimum level to blank) will result in getting Info level / debug level events as well. 

I assume that at some point the target is setting the event level not according to what seq expects, maybe?

**Comment by nblumhardt** [comment] 2018-05-18 01:16
Hi @corrtarr, thanks for getting in touch.

This is a known issue with API key filtering - https://github.com/datalust/seq-tickets/issues/680 - we'll be extending the set of recognized levels in v5. Sorry about the inconvenience!

I'll close this here as it's a duplicate of the linked issue, which we're tracking.

**Closed by nblumhardt** 2018-05-18 01:16 UTC
Labels: bug, duplicate
