### ISSUE TITLE
could not work with nlog5.0x

### ISSUE THREAD

**Issue by gwnpeter** [datalust/nlog-targets-seq#64] opened 2022-06-26 08:28 UTC
could not work with nlog5.0x
it is good with nlog4.7.15

version:
NLog.Targets.Seq V2.10 
net4.72 / net6.0
Seq 2021.4

**Comment by snakefoot** [comment] 2022-06-26 11:29
Duplicate of #59 ?

**Comment by gwnpeter** [comment] 2022-08-22 04:22
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment] 2022-08-22 04:23
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment] 2022-08-22 04:23
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment] 2022-08-22 04:24
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment] 2022-08-22 04:25
fixed！

**Comment by gwnpeter** [comment] 2022-11-17 06:15
close

**Closed** 2022-11-17 22:31 UTC
